# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='plt_icon',
            field=models.URLField(default='', verbose_name='第三方平台的头像URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='prem_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
